apiVersion: v1
kind: Namespace
metadata:
  name: netpol-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: netpol-ns
  labels:
    role: backend
spec:
  containers:
  - name: backend
    image: viktoruj/ping_pong:alpine
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: netpol-ns
  labels:
    role: frontend
spec:
  containers:
  - name: frontend
    image: viktoruj/ping_pong:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: other
  namespace: netpol-ns
  labels:
    role: other
spec:
  containers:
  - name: other
    image: viktoruj/ping_pong:alpine
