apiVersion: v1
kind: Namespace
metadata:
  name: ingress-basic-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: ingress-basic-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-deploy
  template:
    metadata:
      labels:
        app: web-deploy
    spec:
      containers:
      - name: web-deploy
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: ingress-basic-ns
spec:
  selector:
    app: web-deploy
  ports:
  - port: 80
    targetPort: 80
