apiVersion: v1
kind: Namespace
metadata:
  name: tier-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: tier-ns
  labels:
    role: api
spec:
  containers:
  - name: api-pod
    image: viktoruj/ping_pong:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  namespace: tier-ns
  labels:
    role: worker
spec:
  containers:
  - name: worker-pod
    image: viktoruj/ping_pong:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: tier-ns
  labels:
    role: db
spec:
  containers:
  - name: db-pod
    image: viktoruj/ping_pong:alpine
    ports:
    - containerPort: 8080
