apiVersion: v1
kind: Namespace
metadata:
  name: tls-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: tls-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: secure-app
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secure-svc
  namespace: tls-ns
spec:
  selector:
    app: secure-app
  ports:
  - port: 80
    targetPort: 80
