apiVersion: v1
kind: Namespace
metadata:
  name: fix-np-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  namespace: fix-np-ns
  labels:
    role: gateway
spec:
  containers:
  - name: gateway
    image: viktoruj/ping_pong:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: api-service
  namespace: fix-np-ns
  labels:
    role: api
spec:
  containers:
  - name: api-service
    image: viktoruj/ping_pong:alpine
    ports:
    - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway
  namespace: fix-np-ns
spec:
  podSelector:
    matchLabels:
      role: api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: api
    ports:
    - protocol: TCP
      port: 8080
