apiVersion: v1
kind: Namespace
metadata:
  name: debug-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  namespace: debug-ns
spec:
  containers:
  - name: broken-pod
    image: nginx:alpine
    command: ["sh", "-c", "exit 1"]
